services:
  postgres:
    image: postgres:16
    container_name: billing_postgres
    environment:
      POSTGRES_DB: billing_engine
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: billing_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
